#!/usr/bin/env bash
set -euo pipefail

DMEDITOR="emacs"

declare -a options=(
"alacritty - $HOME/.config/alacritty/alacritty.yml"
"bash = $HOME/.bashrc"
"bspwm - $HOME/.config/bspwm/bspwmrc"
"dmenu - $HOME/git/dmenu-5.0/config.def.h"
"dunst - $HOME/.config/dunst/dunstrc"
"dwm - $HOME/.config/dwm/config.def.h"
"fish - $HOME/.config/fish/config.fish"
"i3 - $HOME/.config/i3/config"
"kitty - $HOME/.config/kitty/kitty.conf"
"neovim (plugins) - $HOME/.config/nvim/plugins.vim"
"neovim (config) - $HOME/.config/nvim/init.vim"
"picom - $HOME/.config/picom/picom.conf"
"qtile - $HOME/.config/qtile/config.py"
"st - $HOME/git/st/config.def.h"
"sxhkd - $HOME/.config/sxhkd/sxhkdrc"
"zprezto - $HOME/.zpreztorc"
"zsh - $HOME/.zshrc"
"quit"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 7 -p 'Configs:')

if [[ "$choice" == "quit" ]]; then
	echo "Program terminated." && exit 1

elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMEDITOR "$cfg"

else
	notify-send "Program terminated." && exit 1
fi
