#!/usr/bin/env bash
set -euo pipefail

DMEDITOR="emacs"
cd ~/lang/python/

rm -rf ~/.programs.txt
for entry in ~/lang/python/*
do
    # echo $entry >> ~/.programs.txt
    echo $entry >> ~/.programs.txt
done
for entry in ~/lang/python/nogit
do
    echo $entry >> ~/.programs.txt
done

declare -a options=(
    $(cat ~/.programs.txt)
    "quit"
)

choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -l 7 -p 'Programs:')

if [[ "$choice" == "quit" ]]; then
    (notify-send Program Terminated) && exit
elif [ "$choice" ];then
    cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
    $DMEDITOR "$cfg"

else
    notify-send "Program terminated." && exit 1
fi

