#!/usr/bin/env bash
set -euo pipefail

cmd="switch.py"

declare -a options=(
"Ashes"
"Dracula"
"Everforest"
"Frappe"
"Latte"
"Macchiato"
"Mocha"
"Nord"
"One"
"Palenight"
"quit"
)

choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p 'Configs:')

if [[ "$choice" == "quit" ]]; then
	echo "Program terminated." && exit 1

elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$cmd "$cfg"

else
	notify-send "Program terminated." && exit 1
fi
