#!/usr/bin/env bash
set -euo pipefail

rm -rf ~/.programs.txt

for entry in ~/python/*.py
do
    echo $entry >> ~/.programs.txt
done

declare -a options=(
    $(cat ~/.programs.txt)
    "quit"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 7 -p 'Programs:')

if [[ "$choice" == "quit" ]]; then
    (notify-send Program Terminated) && exit
elif [ "$choice" ];then
    cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
    python3 "$cfg"

else
    notify-send "Program terminated." && exit 1
fi

